---

AllCops:
  DisabledByDefault: true

  DisplayCopNames: true
  DisplayStyleGuide: true

  TargetRubyVersion: 2.3

Metrics:
  Enabled: false

Layout/CommentIndentation:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails

Layout/Tab:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/TrailingBlankLines:
  Enabled: true

Style/HashSyntax:
  Enabled: true
